#!/usr/bin/env osascript
# Returns the current playing song in iTunes for OSX

tell application "iTunes"
	if it is running then
		if player state is playing then
			set track_title to name of the current track
			set artist_name to artist of the current track
			if artist_name > 0 then
				"♫ " & artist_name & " - " & track_title
			else
				"♫ " & "[???] - " & track_title
			end if
		end if
	end if
end tell
